FROM openjdk:8-alpine

RUN ["mkdir", "/usr/src"]
RUN ["mkdir", "/usr/src/app"]
RUN ["mkdir", "/usr/src/app/config"]
RUN ["mkdir", "/usr/src/app/secret"]
RUN ["mkdir", "/usr/src/app/block-seq"]

COPY ./bin/client-app-0.1.jar /usr/lib/clientapp.jar
