echo "Creating channels"
CORE_PEER_ADDRESS=peer0.further.com:7051 CORE_PEER_LOCALMSPID="further" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp peer channel create -o orderer1:7050 -c green -f ./channel-artifacts/green.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt
CORE_PEER_ADDRESS=peer0.further.com:7051 CORE_PEER_LOCALMSPID="further" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp peer channel create -o orderer1:7050 -c blue  -f ./channel-artifacts/blue.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt

echo "Joining Peers to Green Airline Channel"
CORE_PEER_ADDRESS=peer0.green-airline.com:7051  CORE_PEER_LOCALMSPID="green-airline"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-airline.com/users/Admin@green-airline.com/msp   CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-airline.com/peers/peer0.green-airline.com/tls/ca.crt   peer channel join -b green.block
CORE_PEER_ADDRESS=peer0.green-agencies.com:7051 CORE_PEER_LOCALMSPID="green-agencies" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-agencies.com/users/Admin@green-agencies.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-agencies.com/peers/peer0.green-agencies.com/tls/ca.crt peer channel join -b green.block
CORE_PEER_ADDRESS=peer0.further.com:7051        CORE_PEER_LOCALMSPID="further"        CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp               CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/peers/peer0.further.com/tls/ca.crt               peer channel join -b green.block

echo "joining Peers to Blue Airline Channel"
CORE_PEER_ADDRESS=peer0.blue-airline.com:7051  CORE_PEER_LOCALMSPID="blue-airline"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-airline.com/users/Admin@blue-airline.com/msp   CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-airline.com/peers/peer0.blue-airline.com/tls/ca.crt   peer channel join -b blue.block
CORE_PEER_ADDRESS=peer0.blue-agencies.com:7051 CORE_PEER_LOCALMSPID="blue-agencies" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-agencies.com/users/Admin@blue-agencies.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-agencies.com/peers/peer0.blue-agencies.com/tls/ca.crt peer channel join -b blue.block
CORE_PEER_ADDRESS=peer0.further.com:7051       CORE_PEER_LOCALMSPID="further"       CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp             CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/peers/peer0.further.com/tls/ca.crt             peer channel join -b blue.block

echo "Updating Green Airline Channel for Anchor Peers"
CORE_PEER_ADDRESS=peer0.further.com:7051        CORE_PEER_LOCALMSPID="further"        CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp               peer channel update -f ./channel-artifacts/further-green-anchor.tx        -c green -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt
CORE_PEER_ADDRESS=peer0.green-airline.com:7051  CORE_PEER_LOCALMSPID="green-airline"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-airline.com/users/Admin@green-airline.com/msp   peer channel update -f ./channel-artifacts/green-airline-green-anchor.tx  -c green -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt
CORE_PEER_ADDRESS=peer0.green-agencies.com:7051 CORE_PEER_LOCALMSPID="green-agencies" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-agencies.com/users/Admin@green-agencies.com/msp peer channel update -f ./channel-artifacts/green-agencies-green-anchor.tx -c green -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt

echo "Updating Blue Airline Channel for Anchor Peers"
CORE_PEER_ADDRESS=peer0.further.com:7051       CORE_PEER_LOCALMSPID="further"       CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp             peer channel update -f ./channel-artifacts/further-blue-anchor.tx       -c blue -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt
CORE_PEER_ADDRESS=peer0.blue-airline.com:7051  CORE_PEER_LOCALMSPID="blue-airline"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-airline.com/users/Admin@blue-airline.com/msp   peer channel update -f ./channel-artifacts/blue-airline-blue-anchor.tx  -c blue -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt
CORE_PEER_ADDRESS=peer0.blue-agencies.com:7051 CORE_PEER_LOCALMSPID="blue-agencies" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-agencies.com/users/Admin@blue-agencies.com/msp peer channel update -f ./channel-artifacts/blue-agencies-blue-anchor.tx -c blue -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt
