echo "Installing public chaincode on each peer"
CORE_PEER_ADDRESS=peer0.greenairline.com:7051  CORE_PEER_LOCALMSPID="GreenAirlineMSP"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/greenairline.com/users/Admin@greenairline.com/msp   CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/greenairline.com/peers/peer0.greenairline.com/tls/ca.crt   peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.greenagencies.com:7051 CORE_PEER_LOCALMSPID="GreenAgenciesMSP" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/greenagencies.com/users/Admin@greenagencies.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/greenagencies.com/peers/peer0.greenagencies.com/tls/ca.crt peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.blueairline.com:7051   CORE_PEER_LOCALMSPID="BlueAirlineMSP"   CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blueairline.com/users/Admin@blueairline.com/msp     CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blueairline.com/peers/peer0.blueairline.com/tls/ca.crt     peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.blueagencies.com:7051  CORE_PEER_LOCALMSPID="BlueAgenciesMSP"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blueagencies.com/users/Admin@blueagencies.com/msp   CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blueagencies.com/peers/peer0.blueagencies.com/tls/ca.crt   peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.bsps.com:7051        CORE_PEER_LOCALMSPID="BspsMSP"        CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bsps.com/users/Admin@bsps.com/msp               CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bsps.com/peers/peer0.bsps.com/tls/ca.crt               peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02

echo "Initializing bsp chaincode for channel green. It is only done once by a single peer."
CORE_PEER_ADDRESS=peer0.bsps.com:7051 CORE_PEER_LOCALMSPID="BspsMSP" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bsps.com/users/Admin@bsps.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bsps.com/peers/peer0.bsps.com/tls/ca.crt peer chaincode instantiate -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt -C green -n bspcc -v 1.0 -c '{"Args":["init","a","100","b","200"]}' -P "OutOf(2, 'BspsMSP.member', 'GreenAirlineMSP.member', 'GreenAgenciesMSP.member')" --collections-config /opt/gopath/src/github.com/hyperledger/fabric/peer/private-collections/green-private.json

echo "Initializing bsp chaincode for channel blue. It is only done once by a single peer."
CORE_PEER_ADDRESS=peer0.bsps.com:7051 CORE_PEER_LOCALMSPID="BspsMSP" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bsps.com/users/Admin@bsps.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bsps.com/peers/peer0.bsps.com/tls/ca.crt peer chaincode instantiate -o orderer1:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer1.orderer.com/tls/ca.crt -C blue  -n bspcc -v 1.0 -c '{"Args":["init","a","100","b","200"]}' -P "OutOf(2, 'BspsMSP.member', 'BlueAirlineMSP.member', 'BlueAgenciesMSP.member' )"
