echo "Installing public chaincode on each peer"
CORE_PEER_ADDRESS=peer0.green-airline.com:7051  CORE_PEER_LOCALMSPID="green-airline"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-airline.com/users/Admin@green-airline.com/msp   CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-airline.com/peers/peer0.green-airline.com/tls/ca.crt   peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.green-agencies.com:7051 CORE_PEER_LOCALMSPID="green-agencies" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-agencies.com/users/Admin@green-agencies.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/green-agencies.com/peers/peer0.green-agencies.com/tls/ca.crt peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.blue-airline.com:7051   CORE_PEER_LOCALMSPID="blue-airline"   CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-airline.com/users/Admin@blue-airline.com/msp     CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-airline.com/peers/peer0.blue-airline.com/tls/ca.crt     peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.blue-agencies.com:7051  CORE_PEER_LOCALMSPID="blue-agencies"  CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-agencies.com/users/Admin@blue-agencies.com/msp   CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/blue-agencies.com/peers/peer0.blue-agencies.com/tls/ca.crt   peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02
CORE_PEER_ADDRESS=peer0.further.com:7051        CORE_PEER_LOCALMSPID="further"        CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp               CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/peers/peer0.further.com/tls/ca.crt               peer chaincode install -n bspcc -v 1.0 -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02

echo "Initializing bsp chaincode for channel green. It is only done once by a single peer."
CORE_PEER_ADDRESS=peer0.further.com:7051 CORE_PEER_LOCALMSPID="further" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/peers/peer0.further.com/tls/ca.crt peer chaincode instantiate -o orderer:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer.orderer.com/tls/ca.crt -C green -n bspcc -v 1.0 -c '{"Args":["init","a","100","b","200"]}' -P "OutOf(2, 'further.member', 'green-airline.member', 'green-agencies.member')"

echo "Initializing bsp chaincode for channel blue. It is only done once by a single peer."
CORE_PEER_ADDRESS=peer0.further.com:7051 CORE_PEER_LOCALMSPID="further" CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/users/Admin@further.com/msp CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/further.com/peers/peer0.further.com/tls/ca.crt peer chaincode instantiate -o orderer:7050 --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.com/orderers/orderer.orderer.com/tls/ca.crt -C blue  -n bspcc -v 1.0 -c '{"Args":["init","a","100","b","200"]}' -P "OutOf(2, 'further.member', 'blue-airline.member', 'blue-agencies.member' )"
